shell.run("mkdir", "ui")
shell.run("mkdir", "network")
shell.run("mkdir", "pages")

shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/main.lua", "main.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/ui/navbar.lua", "ui/navbar.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/ui/keypad.lua", "ui/keypad.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/network/sync.lua", "network/sync.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/pages/dashboard.lua", "pages/dashboard.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/pages/autocraft.lua", "pages/autocraft.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/pages/turtle_map.lua", "pages/turtle_map.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/pages/turtle_analyse.lua", "pages/turtle_analyse.lua")
shell.run("wget", "https://raw.githubusercontent.com/anaa98fdgdfgw/controller/refs/heads/main/CC/pages/reactor.lua", "pages/reactor.lua")

-- Téléchargement de Basalt 2 (officiel)
print("[Installer] Téléchargement de Basalt 2 (UI)...")
shell.run("wget run https://raw.githubusercontent.com/Pyroxenium/Basalt2/main/install.lua -r")
print("[Installer] Basalt 2 installé avec succès !")

print("Installation terminée ! Utilise la commande main pour démarrer.")
